apiVersion: v1
kind: Namespace
metadata:
  name: mpi-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
  namespace: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mpi-operator
  template:
    metadata:
      labels:
        name: mpi-operator
    spec:
      serviceAccountName: mpi-operator
      containers:
      - name: mpi-operator
        image: kubeflownotebookswg/mpi-operator:v0.4.0
        command: ["/manager"]
        args:
        - --config=/etc/config/config.yaml
        - --zap-log-level=info
        - --zap-time-encoding=iso8601
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
          readOnly: true
      volumes:
      - configMap:
          name: mpi-operator-config
        name: config-volume
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpi-operator
  namespace: mpi-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpi-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["kubeflow.org"]
  resources: ["mpijobs"]
  verbs: ["*"]
- apiGroups: ["kubeflow.org"]
  resources: ["mpijobs/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mpi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mpi-operator
subjects:
- kind: ServiceAccount
  name: mpi-operator
  namespace: mpi-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mpi-operator-config
  namespace: mpi-operator
data:
  config.yaml: |
    mpiJob:
      cleanPodPolicy: "Running"