apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: scorehive-cluster
  namespace: scorehive
spec:
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - name: scorehive-launcher
            image: gcr.io/PROJECT_ID/scorehive-mpi:v1.0.0
            command: 
            - mpirun
            - --allow-run-as-root
            - --hostfile
            - /etc/mpi/hostfile
            - --np
            - "5"
            - /app/build/ScoreHiveCluster
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            env:
            - name: DEBUG
              value: "0"
            volumeMounts:
            - name: ssh-auth
              mountPath: /root/.ssh
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: ssh-auth
            secret:
              secretName: mpi-ssh-key
              defaultMode: 0600
    Master:
      replicas: 1
      template:
        spec:
          containers:
          - name: scorehive-master
            image: gcr.io/PROJECT_ID/scorehive-mpi:v1.0.0
            ports:
            - containerPort: 8080
              name: http
            - containerPort: 22
              name: ssh
            resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 500m
                memory: 512Mi
            livenessProbe:
              exec:
                command: 
                - /bin/sh
                - -c
                - 'echo "test" | timeout 3 nc localhost 8080 || exit 1'
              initialDelaySeconds: 30
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
            readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 10
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 3
            env:
            - name: DEBUG
              value: "0"
            - name: OMPI_ALLOW_RUN_AS_ROOT
              value: "1"
            - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
              value: "1"
            volumeMounts:
            - name: ssh-auth
              mountPath: /root/.ssh
              readOnly: true
          volumes:
          - name: ssh-auth
            secret:
              secretName: mpi-ssh-key
              defaultMode: 0600
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - name: scorehive-worker
            image: gcr.io/PROJECT_ID/scorehive-mpi:v1.0.0
            ports:
            - containerPort: 22
              name: ssh
            resources:
              limits:
                cpu: 2000m
                memory: 2Gi
              requests:
                cpu: 1000m
                memory: 1Gi
            env:
            - name: DEBUG
              value: "0"
            - name: OMPI_ALLOW_RUN_AS_ROOT
              value: "1"
            - name: OMPI_ALLOW_RUN_AS_ROOT_CONFIRM
              value: "1"
            volumeMounts:
            - name: ssh-auth
              mountPath: /root/.ssh
              readOnly: true
          volumes:
          - name: ssh-auth
            secret:
              secretName: mpi-ssh-key
              defaultMode: 0600