apiVersion: v1
kind: Secret
metadata:
  name: mpi-ssh-key
  namespace: scorehive
type: Opaque
data:
  # SSH key pair for MPI communication (base64 encoded)
  # Generate with: ssh-keygen -t rsa -b 4096 -f mpi_key -N ""
  # Then: cat mpi_key | base64 -w 0
  id_rsa: LS0tLS1CRUdJTi[...base64 encoded private key...]
  # cat mpi_key.pub | base64 -w 0
  id_rsa.pub: c3NoLXJzYSBBQUFBQjN[...base64 encoded public key...]
  # cat mpi_key.pub >> authorized_keys && cat authorized_keys | base64 -w 0
  authorized_keys: c3NoLXJzYSBBQUFBQjN[...base64 encoded authorized_keys...]
  # SSH config for passwordless connection
  config: |
    Host *
        StrictHostKeyChecking no
        UserKnownHostsFile /dev/null
        LogLevel ERROR