services:
  postgres:
    image: postgres:16
    container_name: scorehive-postgres
    hostname: scorehive-postgres
    networks:
      - scorehive-net
    environment:
      POSTGRES_DB: scorehive_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./database/scheme.sql:/docker-entrypoint-initdb.d/10-scheme.sql
      - ./database/functions.sql:/docker-entrypoint-initdb.d/20-functions.sql
      - postgres_data:/var/lib/postgresql/data

  mpi-master:
    image: scorehive-mpi:latest
    container_name: scorehive-master
    hostname: mpi-master
    networks:
      - scorehive-net
    ports:
      - "8080:8080"
    volumes:
      - ./hostfile:/app/hostfile:ro
    environment:
      - DEBUG=1
      - PGDATABASE=scorehive_db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGHOST=scorehive-postgres
      - PGPORT=5432
    depends_on:
      - postgres
      - mpi-worker1
      - mpi-worker2
      - mpi-worker3

  mpi-worker1:
    image: scorehive-mpi:latest
    container_name: scorehive-worker1
    hostname: mpi-worker1
    networks:
      - scorehive-net
    environment:
      - DEBUG=1
      - PGDATABASE=scorehive_db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGHOST=scorehive-postgres
      - PGPORT=5432
    depends_on:
      - postgres

  mpi-worker2:
    image: scorehive-mpi:latest
    container_name: scorehive-worker2
    hostname: mpi-worker2
    networks:
      - scorehive-net
    environment:
      - DEBUG=1
      - PGDATABASE=scorehive_db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGHOST=scorehive-postgres
      - PGPORT=5432
    depends_on:
      - postgres

  mpi-worker3:
    image: scorehive-mpi:latest
    container_name: scorehive-worker3
    hostname: mpi-worker3
    networks:
      - scorehive-net
    environment:
      - DEBUG=1
      - PGDATABASE=scorehive_db
      - PGUSER=postgres
      - PGPASSWORD=mysecretpassword
      - PGHOST=scorehive-postgres
      - PGPORT=5432
    depends_on:
      - postgres

networks:
  scorehive-net:
    driver: bridge

volumes:
  postgres_data: