apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: scorehive-mpi
spec:
  slotsPerWorker: 1 # Núm. de slots MPI por pod worker
  runPolicy:
    cleanPodPolicy: Running # Limpiar pods al terminar
  mpiReplicaSpecs:
    Launcher:
      replicas: 1 # Pod maestro (ejecutará mpirun)
      template:
        spec:
          containers:
            - name: mpi-launcher
              image: gcr.io/tu-proyecto/scorehive-mpi:latest # Usa tu imagen en GCR
              command: ["mpirun"]
              args:
                - "--hostfile"
                - "/etc/mpi/hostfile"
                - "-np"
                - "3" # Total procesos: 1 launcher + 2 workers
                - "/app/build/your_mpi_program" # Ruta a tu binario
              env:
                - name: DEBUG
                  value: "1"
              resources:
                limits:
                  cpu: "1"
                  memory: "1Gi"
    Worker:
      replicas: 2 # Número de pods worker
      template:
        spec:
          containers:
            - name: mpi-worker
              image: gcr.io/tu-proyecto/scorehive-mpi:latest # Misma imagen
              resources:
                limits:
                  cpu: "1"
                  memory: "2Gi"
